In [2]:
import numpy as np

In [3]:
y = np.array([12, 14, 10, 6, 43])
yhat = np.array([10, 13, 7, 14, 40])

In [4]:
diff = y-yhat
diff_bool = (diff>0).astype(int)
diff_bool

array([1, 1, 1, 0, 1])

In [13]:
m0 = (y*diff_bool)
m1 = m0 + (m0 == 0).astype(int)
flt_error = (diff*diff_bool)/m1
flt_error

array([0.16666667, 0.07142857, 0.3       , 0.        , 0.06976744])

In [14]:
sum(flt_error)

0.6078626799557032

In [7]:
y*diff_bool

array([12, 14, 10,  0, 43])

In [10]:
np.sum(flt_error)

nan

In [12]:
(y*diff_bool == 0).astype(int)

array([0, 0, 0, 1, 0])

In [ ]:
def undercastingError(y, yhat):
    diff = y-yhat
    diff_bool = (diff>0).astype(int)
    m0 = (y*diff_bool)
    m1 = m0 + (m0 == 0).astype(int)
    flt_error = (diff*diff_bool)/m1
    return sum(flt_error)

***